-
  name: play
  hosts: client1
  vars:
    app: httpd
    folder: apache-logs
    file: apache-logs.logs
  tasks:
    - name: code to install app
      yum:
        name: '{{app}}'
        state: present

    - name: code to start
      service:
        name: '{{app}}'
        state: started

    - name: code to enable app
      service:
        name: '{{app}}'
        enabled: yes 

    - name: code to create dir
      file:
        path: /opt/'{{folder}}'
        state: directory

    - name: code to create file
      file:
        path: /opt/'{{folder}}'/'{{file}}'
        state: present
        line: 'Apache is suvvessfilly linked'

    - name: code to write message
      lineinfile:
        path: /opt/'{{folder}}'/'{{file}}'
        state: present
        line: 'Apache is succesfilly installed'

    - name: create index
      file:
        file:
          path: /var/www/html/index.html
          state: touch

    - name: code
      lineinfile:
        path: /var/www/html/index.html
        state: present
        line: '<html>
        <body> Anbidfdlbebebeb
        </body>
        </html>'
